use_frameworks!

target 'ActionStageExtensions_Example' do
  pod 'ActionStageExtensions', :path => '../'

  target 'ActionStageExtensions_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
